# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vkontakte' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vkontakte
	pod 'Alamofire'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'RealmSwift'
	pod 'Kingfisher', "~> 5.7.1"
	pod "PromiseKit", "~> 6.8"
	pod 'PromiseKit/Alamofire' 
end
